### ISSUE TITLE
Error in rb tree implementation

### ISSUE THREAD

**Issue by a1983** [LemonPi/data#1]
Such code not passed validation:

```
int main(int argc, char *argv[]) {
  sal::Basic_tree< int > s;
  s.insert( 3 );
  s.insert( 1 );
  s.insert( 2 );
  assert( s.valid() );
  return 0;
}
```

Unfortunately, I can't found what's wrong with algorithm.

**Comment by LemonPi** [comment]
Thanks - fixed in 7d1c5 and added it to datatest's tree_test unit testing.
It was a problem with rb_insert_fixup using stale parent pointers.

**Comment by LemonPi** [comment]
Hey a1983, _data_ has stopped being a submodule of sal, so I recommend you clone [_sal_'s repo](https://github.com/LemonPi/sal) instead, as changes will only be made there. This repository will eventually get discontinued.

**Comment by a1983** [comment]
You are welcome. It seems ok now.
P.S. Your library is pretty good.
